{% set name = "esgf-pyclient" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d79fafc6ec2a1eff9645e098554103f1e9f3c270947b1ac4f4a8a07fece59f3b

build:
  number: 5
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python {{ python_min }}
    - setuptools_scm
    - pip !=21.3
  run:
    - python >={{ python_min }}
    - jinja2
    - requests
    - requests-cache >=0.6
    - webob >=1.8.9  # supports Python 3.13 github.com/ESGF/esgf-pyclient/pull/109
    - defusedxml
    - myproxyclient >=2.1.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyesgf
    - pyesgf.search
    - pyesgf.security
    - pyesgf.logon

about:
  home: http://esgf-pyclient.readthedocs.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A library interacting with ESGF services within Python

extra:
  recipe-maintainers:
    - valeriupredoi
    - agoodm
    - jarifibrahim
    - agstephens
    - cehbrecht
    - bouweandela
